# Generated by Django 6.1 on 2026-08-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('full_description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='built-environment', max_length=100)),
                ('features', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, default='/assets/hvac_bim.jpg', max_length=500)),
                ('demo_url', models.URLField(blank=True, default='')),
                ('documentation_url', models.URLField(blank=True, default='')),
                ('purchase_url', models.URLField(blank=True, default='')),
                ('published', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('full_description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Product', 'Product Engineering'), ('MEP', 'MEP & HVAC Systems'), ('Structural', 'Structural Steel & Concrete')], default='MEP', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_file_url', models.CharField(max_length=500)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_format', models.CharField(max_length=50)),
                ('converted_file_url', models.CharField(blank=True, default='', max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, default='/assets/hero_building.jpg', max_length=500)),
                ('conversion_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=50)),
                ('conversion_error', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('profile_image', models.CharField(blank=True, default='/assets/team-placeholder.jpg', max_length=500)),
                ('profile_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_pdf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default='/', max_length=255)),
                ('session_id', models.CharField(max_length=255)),
                ('referrer', models.CharField(default='direct', max_length=500)),
                ('is_unique_visit', models.BooleanField(default=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('billing_type', models.CharField(choices=[('free', 'Free'), ('one_time', 'One-time Purchase'), ('monthly', 'Monthly Subscription'), ('annual', 'Annual Subscription'), ('custom', 'Custom Pricing')], default='one_time', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.aiagent')),
            ],
        ),
    ]
